version: 2
updates:
  - package-ecosystem: gomod
    directory: /
    schedule:
      interval: weekly
    labels:
      - dependencies
    reviewers:
      - dengmengmian

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: monthly
    labels:
      - ci
      - dependencies
